# Pandas Intro

Pandas is a python library that helps you investigate and prep your data (e. g. cleaning, grouping, aggregating, plotting, joining). You can use it in Python notebooks like this one.

To install pandas:
`pip install pandas`

To run a notebook (Python must be downloaded on your computer):
In your terminal:
- Navigate to the folder that contains your file
- Run `jupyter notebook`

# Import Pandas

In [1]:
import pandas as pd

# Loading Data

NYC Open Data 2018 Central Park Squirrel Census: https://data.cityofnewyork.us/Environment/2018-Central-Park-Squirrel-Census-Squirrel-Data/vfnx-vebw/data_preview

In [2]:
# load the squirrels.csv file
squirrels_df = pd.read_csv('data/squirrels.csv')

Dataframes are 2D structures defined by rows and columns (like tables)

In [3]:
# look at the first few rows
squirrels_df.head()

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,...,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9561344937861 40.7940823884086)
1,-73.968857,40.783783,21B-AM-1019-04,21B,AM,10192018,4,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9688574691102 40.7837825208444)
2,-73.974281,40.775534,11B-PM-1014-08,11B,PM,10142018,8,NaN,Gray,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.97428114848522 40.775533619083)
3,-73.959641,40.790313,32E-PM-1017-14,32E,PM,10172018,14,Adult,Gray,NaN,...,False,False,False,False,False,False,False,True,NaN,POINT (-73.9596413903948 40.7903128889029)
4,-73.970268,40.776213,13E-AM-1017-05,13E,AM,10172018,5,Adult,Gray,Cinnamon,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9702676472613 40.7762126854894)

In [4]:
# see all the columns
pd.set_option('display.max_columns', None)

# look at the last few rows
squirrels_df.tail()

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,Combination of Primary and Highlight Color,Color notes,Location,Above Ground Sighter Measurement,Specific Location,Running,Chasing,Climbing,Eating,Foraging,Other Activities,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long
3018,-73.963943,40.790868,30B-AM-1007-04,30B,AM,10072018,4,Adult,Gray,NaN,Gray+,NaN,Ground Plane,FALSE,NaN,False,False,False,True,True,NaN,False,False,False,False,False,False,False,True,NaN,POINT (-73.9639431360458 40.7908677445466)
3019,-73.970402,40.782560,19A-PM-1013-05,19A,PM,10132018,5,Adult,Gray,White,Gray+White,NaN,Ground Plane,FALSE,NaN,False,False,False,False,True,NaN,False,False,False,False,False,False,True,False,NaN,POINT (-73.9704015859639 40.7825600069973)
3020,-73.966587,40.783678,22D-PM-1012-07,22D,PM,10122018,7,Adult,Gray,"Black, Cinnamon, White","Gray+Black, Cinnamon, White",NaN,Ground Plane,FALSE,NaN,False,False,False,True,True,NaN,False,False,False,False,False,False,True,False,NaN,POINT (-73.9665871993517 40.7836775064883)
3021,-73.963994,40.789915,29B-PM-1010-02,29B,PM,10102018,2,NaN,Gray,"Cinnamon, White","Gray+Cinnamon, White",NaN,Ground Plane,FALSE,NaN,False,False,False,True,False,NaN,False,False,False,False,False,False,True,False,NaN,POINT (-73.9639941227864 40.7899152327912)
3022,-73.975479,40.769640,5E-PM-1012-01,05E,PM,10122018,1,Adult,Cinnamon,"Gray, White","Cinnamon+Gray, White",NaN,Ground Plane,FALSE,NaN,False,False,False,True,True,NaN,False,False,False,False,False,True,False,False,NaN,POINT (-73.9754794191553 40.7696404489025)

In [5]:
# seeing NaN in these columns:
# "Age", "Highlight Fur Color", "Color notes", "Specific Location", "Other Activities", "Other Interactions"

# clean up the data
squirrels_df.fillna("",inplace=True)

squirrels_df.head()

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,Combination of Primary and Highlight Color,Color notes,Location,Above Ground Sighter Measurement,Specific Location,Running,Chasing,Climbing,Eating,Foraging,Other Activities,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,,,,+,,,,,False,False,False,False,False,,False,False,False,False,False,False,False,False,,POINT (-73.9561344937861 40.7940823884086)
1,-73.968857,40.783783,21B-AM-1019-04,21B,AM,10192018,4,,,,+,,,,,False,False,False,False,False,,False,False,False,False,False,False,False,False,,POINT (-73.9688574691102 40.7837825208444)
2,-73.974281,40.775534,11B-PM-1014-08,11B,PM,10142018,8,,Gray,,Gray+,,Above Ground,10,,False,True,False,False,False,,False,False,False,False,False,False,False,False,,POINT (-73.97428114848522 40.775533619083)
3,-73.959641,40.790313,32E-PM-1017-14,32E,PM,10172018,14,Adult,Gray,,Gray+,Nothing selected as Primary. Gray selected as ...,,,,False,False,False,True,True,,False,False,False,False,False,False,False,True,,POINT (-73.9596413903948 40.7903128889029)
4,-73.970268,40.776213,13E-AM-1017-05,13E,AM,10172018,5,Adult,Gray,Cinnamon,Gray+Cinnamon,,Above Ground,,on tree stump,False,False,False,False,True,,False,False,False,False,False,False,False,False,,POINT (-73.9702676472613 40.7762126854894)

# Describing

In [6]:
# rows?
len(squirrels_df)

3023

In [7]:
# columns
squirrels_df.columns

Index(['X', 'Y', 'Unique Squirrel ID', 'Hectare', 'Shift', 'Date',
       'Hectare Squirrel Number', 'Age', 'Primary Fur Color',
       'Highlight Fur Color', 'Combination of Primary and Highlight Color',
       'Color notes', 'Location', 'Above Ground Sighter Measurement',
       'Specific Location', 'Running', 'Chasing', 'Climbing', 'Eating',
       'Foraging', 'Other Activities', 'Kuks', 'Quaas', 'Moans', 'Tail flags',
       'Tail twitches', 'Approaches', 'Indifferent', 'Runs from',
       'Other Interactions', 'Lat/Long'],
      dtype='object')

In [8]:
# column data types
squirrels_df.dtypes

X                                             float64
Y                                             float64
Unique Squirrel ID                             object
Hectare                                        object
Shift                                          object
Date                                            int64
Hectare Squirrel Number                         int64
Age                                            object
Primary Fur Color                              object
Highlight Fur Color                            object
Combination of Primary and Highlight Color     object
Color notes                                    object
Location                                       object
Above Ground Sighter Measurement               object
Specific Location                              object
Running                                          bool
Chasing                                          bool
Climbing                                         bool
Eating                                           bool
Foraging                                         bool
Other Activities                               object
Kuks                                             bool
Quaas                                            bool
Moans                                            bool
Tail flags                                       bool
Tail twitches                                    bool
Approaches                                       bool
Indifferent                                      bool
Runs from                                        bool
Other Interactions                             object
Lat/Long                                       object
dtype: object

In [9]:
# statistical summary of the numeric columns
squirrels_df.describe()

                 X            Y          Date  Hectare Squirrel Number
count  3023.000000  3023.000000  3.023000e+03              3023.000000
mean    -73.967184    40.780853  1.011949e+07                 4.123718
std       0.007726     0.010285  4.246671e+04                 3.096492
min     -73.981159    40.764911  1.006202e+07                 1.000000
25%     -73.973102    40.771676  1.008202e+07                 2.000000
50%     -73.968594    40.778166  1.012202e+07                 3.000000
75%     -73.960189    40.791219  1.014202e+07                 6.000000
max     -73.949722    40.800119  1.020202e+07                23.000000

In [10]:
# see most common values in a column of strings
squirrels_df['Primary Fur Color'].value_counts()

Primary Fur Color
Gray        2473
Cinnamon     392
Black        103
              55
Name: count, dtype: int64

In [11]:
# see breakdown of true/false for boolean columns
squirrels_df['Running'].value_counts(normalize=True)

Running
False    0.758518
True     0.241482
Name: proportion, dtype: float64

# Finding and updating

In [12]:
# locate a row, delete it
    #are there any rows with notes that we want to delete?
squirrels_df[squirrels_df['Color notes'] != ""]

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,Combination of Primary and Highlight Color,Color notes,Location,Above Ground Sighter Measurement,Specific Location,Running,Chasing,Climbing,Eating,Foraging,Other Activities,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long
3,-73.959641,40.790313,32E-PM-1017-14,32E,PM,10172018,14,Adult,Gray,,Gray+,Nothing selected as Primary. Gray selected as ...,,,,False,False,False,True,True,,False,False,False,False,False,False,False,True,,POINT (-73.9596413903948 40.7903128889029)
6,-73.954120,40.793181,36H-AM-1010-02,36H,AM,10102018,2,Adult,Gray,,Gray+,just outside hectare,Ground Plane,FALSE,,False,False,False,False,True,,False,False,False,False,False,False,False,False,,POINT (-73.9541201789795 40.7931811701082)
29,-73.975698,40.775390,10A-PM-1014-01,10A,PM,10142018,1,Adult,Gray,"Black, Cinnamon, White","Gray+Black, Cinnamon, White",Gray & White selected as Primary. Black & Cinn...,Ground Plane,FALSE,in b/w trees,False,False,False,False,True,,False,False,False,False,True,False,True,False,,POINT (-73.9756976076707 40.7753897331918)
57,-73.952819,40.792313,36I-AM-1017-02,36I,AM,10172018,2,Adult,Gray,Cinnamon,Gray+Cinnamon,Cinnamon stripe on back,Ground Plane,FALSE,,False,False,False,False,True,,False,False,False,False,False,False,True,False,,POINT (-73.952819267977 40.7923130402793)
59,-73.959500,40.790337,32E-PM-1017-13,32E,PM,10172018,13,Adult,Gray,,Gray+,Nothing selected as Primary. Gray selected as ...,,,,False,False,False,True,True,,False,False,False,False,False,False,True,False,,POINT (-73.9595002339508 40.7903365788694)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2945,-73.974515,40.770065,6E-PM-1010-03,06E,PM,10102018,3,Adult,Cinnamon,White,Cinnamon+White,white back legs,Ground Plane,FALSE,small open area but w/ 7 large oak trees,False,True,False,True,False,chasing #4,False,False,False,False,False,False,True,False,,POINT (-73.974515099169 40.770065079988605)
2988,-73.964354,40.791757,31A-PM-1017-01,31A,PM,10172018,1,Juvenile,Cinnamon,"Gray, White","Cinnamon+Gray, White","Gray lower back, Gray & Cinnamon selected as P...",Ground Plane,FALSE,,False,False,False,False,True,,False,False,False,False,True,False,False,False,,POINT (-73.9643538221947 40.7917565604735)
3012,-73.964661,40.776979,17I-AM-1014-03,17I,AM,10142018,3,Adult,Gray,"Cinnamon, White","Gray+Cinnamon, White",Cinnamon face,Above Ground,10,,False,False,True,False,False,climbing (dog barked & it ran up tree),False,False,False,False,False,False,True,False,,POINT (-73.964661337306 40.7769785494935)
3014,-73.975916,40.773618,9B-AM-1010-08,09B,AM,10102018,8,Adult,Gray,"Cinnamon, White","Gray+Cinnamon, White","Cinnamon head, White (Almost Silver)",Ground Plane,FALSE,,False,False,False,True,True,,False,False,False,False,True,False,False,False,,POINT (-73.9759163300535 40.7736180793606)
3016,-73.966290,40.784330,23C-AM-1019-01,23C,AM,10192018,1,Adult,Gray,"Cinnamon, White","Gray+Cinnamon, White","Gray & Cinnamon selected as Primary. Gray, Cin...",Above Ground,7,,False,False,True,True,False,eating (on branch),True,False,False,False,False,False,True,False,,POINT (-73.9662895079734 40.7843300758044)

In [13]:
    # maybe get rid of "just outside hectare" row - this squirrel may not be accurately recorded.
    #location is 6
squirrels_df.iloc[6]

X                                                                              -73.95412
Y                                                                              40.793181
Unique Squirrel ID                                                        36H-AM-1010-02
Hectare                                                                              36H
Shift                                                                                 AM
Date                                                                            10102018
Hectare Squirrel Number                                                                2
Age                                                                                Adult
Primary Fur Color                                                                   Gray
Highlight Fur Color
Combination of Primary and Highlight Color                                         Gray+
Color notes                                                         just outside hectare
Location                                                                    Ground Plane
Above Ground Sighter Measurement                                                   FALSE
Specific Location
Running                                                                            False
Chasing                                                                            False
Climbing                                                                           False
Eating                                                                             False
Foraging                                                                            True
Other Activities
Kuks                                                                               False
Quaas                                                                              False
Moans                                                                              False
Tail flags                                                                         False
Tail twitches                                                                      False
Approaches                                                                         False
Indifferent                                                                        False
Runs from                                                                          False
Other Interactions
Lat/Long                                      POINT (-73.9541201789795 40.7931811701082)
Name: 6, dtype: object

In [14]:
#and drop it
squirrels_df.drop(index=6, inplace=True)

In [15]:
#check that it's gone
squirrels_df.iloc[4:8]

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,Combination of Primary and Highlight Color,Color notes,Location,Above Ground Sighter Measurement,Specific Location,Running,Chasing,Climbing,Eating,Foraging,Other Activities,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long
4,-73.970268,40.776213,13E-AM-1017-05,13E,AM,10172018,5,Adult,Gray,Cinnamon,Gray+Cinnamon,,Above Ground,,on tree stump,False,False,False,False,True,,False,False,False,False,False,False,False,False,,POINT (-73.9702676472613 40.7762126854894)
5,-73.968361,40.772591,11H-AM-1010-03,11H,AM,10102018,3,Adult,Cinnamon,White,Cinnamon+White,,,,,False,False,False,False,True,,False,False,False,False,True,False,True,False,,POINT (-73.9683613516225 40.7725908847499)
7,-73.958269,40.791737,33F-AM-1008-02,33F,AM,10082018,2,Adult,Gray,,Gray+,,Ground Plane,FALSE,,False,False,False,False,True,,False,False,False,False,False,False,True,False,,POINT (-73.9582694312289 40.7917367820255)
8,-73.967429,40.782972,21C-PM-1006-01,21C,PM,10062018,1,Adult,Gray,,Gray+,,Ground Plane,FALSE,,False,False,False,False,False,,False,False,False,True,True,False,False,False,,POINT (-73.9674285955293 40.7829723919744)

In [16]:
#create a column of "is this squirrel active?"
squirrels_df['Active'] = squirrels_df['Running'] | squirrels_df['Chasing'] | squirrels_df['Climbing'] | squirrels_df['Eating'] | squirrels_df['Foraging']
squirrels_df.head()

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,Combination of Primary and Highlight Color,Color notes,Location,Above Ground Sighter Measurement,Specific Location,Running,Chasing,Climbing,Eating,Foraging,Other Activities,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long,Active
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,,,,+,,,,,False,False,False,False,False,,False,False,False,False,False,False,False,False,,POINT (-73.9561344937861 40.7940823884086),False
1,-73.968857,40.783783,21B-AM-1019-04,21B,AM,10192018,4,,,,+,,,,,False,False,False,False,False,,False,False,False,False,False,False,False,False,,POINT (-73.9688574691102 40.7837825208444),False
2,-73.974281,40.775534,11B-PM-1014-08,11B,PM,10142018,8,,Gray,,Gray+,,Above Ground,10,,False,True,False,False,False,,False,False,False,False,False,False,False,False,,POINT (-73.97428114848522 40.775533619083),True
3,-73.959641,40.790313,32E-PM-1017-14,32E,PM,10172018,14,Adult,Gray,,Gray+,Nothing selected as Primary. Gray selected as ...,,,,False,False,False,True,True,,False,False,False,False,False,False,False,True,,POINT (-73.9596413903948 40.7903128889029),True
4,-73.970268,40.776213,13E-AM-1017-05,13E,AM,10172018,5,Adult,Gray,Cinnamon,Gray+Cinnamon,,Above Ground,,on tree stump,False,False,False,False,True,,False,False,False,False,False,False,False,False,,POINT (-73.9702676472613 40.7762126854894),True

In [17]:
# condense all of the boolean values into one "Action" column

#possible actions:
actions = ['Running', 'Chasing', 'Climbing', 'Eating', 'Foraging']
#if a squirrel has a "True" in action category, add that category to the "Action" column. If a squirrel has multiple "True" values, concatenate those categories together in the "Action" column.
def concatenate_actions(row):
    action_list = []
    for action in actions:
        if row[action] == True:
            action_list.append(action)
    return ", ".join(action_list)
squirrels_df['Action'] = squirrels_df.apply(concatenate_actions, axis=1)


squirrels_df.head()

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,Combination of Primary and Highlight Color,Color notes,Location,Above Ground Sighter Measurement,Specific Location,Running,Chasing,Climbing,Eating,Foraging,Other Activities,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long,Active,Action
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,,,,+,,,,,False,False,False,False,False,,False,False,False,False,False,False,False,False,,POINT (-73.9561344937861 40.7940823884086),False,
1,-73.968857,40.783783,21B-AM-1019-04,21B,AM,10192018,4,,,,+,,,,,False,False,False,False,False,,False,False,False,False,False,False,False,False,,POINT (-73.9688574691102 40.7837825208444),False,
2,-73.974281,40.775534,11B-PM-1014-08,11B,PM,10142018,8,,Gray,,Gray+,,Above Ground,10,,False,True,False,False,False,,False,False,False,False,False,False,False,False,,POINT (-73.97428114848522 40.775533619083),True,Chasing
3,-73.959641,40.790313,32E-PM-1017-14,32E,PM,10172018,14,Adult,Gray,,Gray+,Nothing selected as Primary. Gray selected as ...,,,,False,False,False,True,True,,False,False,False,False,False,False,False,True,,POINT (-73.9596413903948 40.7903128889029),True,"Eating, Foraging"
4,-73.970268,40.776213,13E-AM-1017-05,13E,AM,10172018,5,Adult,Gray,Cinnamon,Gray+Cinnamon,,Above Ground,,on tree stump,False,False,False,False,True,,False,False,False,False,False,False,False,False,,POINT (-73.9702676472613 40.7762126854894),True,Foraging

# Grouping

In [18]:
# aggregate by a column

#are squirrels of different fur colors active at different times of day?
squirrels_df.groupby('Shift')['Primary Fur Color'].value_counts()

Shift  Primary Fur Color
AM     Gray                 1086
       Cinnamon              180
       Black                  51
                              29
PM     Gray                 1386
       Cinnamon              212
       Black                  52
                              26
Name: count, dtype: int64

In [19]:
#Are there primary fur colors that more highlights than others?
squirrels_df.groupby('Primary Fur Color')['Highlight Fur Color'].value_counts()

Primary Fur Color  Highlight Fur Color
                                              55
Black                                         74
                   Cinnamon                   15
                   Gray                        8
                   Cinnamon, White             3
                   White                       2
                   Gray, White                 1
Cinnamon           Gray                      162
                   White                      94
                                              62
                   Gray, White                58
                   Black                      10
                   Black, White                3
                   Gray, Black                 3
Gray                                         894
                   Cinnamon                  752
                   White                     489
                   Cinnamon, White           265
                   Black, Cinnamon, White     32
                   Black                      24
                   Black, Cinnamon             9
                   Black, White                7
Name: count, dtype: int64

In [20]:
#Do adult or juvenile squirrels forage more?
squirrels_df.groupby('Age')['Foraging'].value_counts()

Age       Foraging
          False         78
          True          43
?         False          3
          True           1
Adult     False       1295
          True        1272
Juvenile  False        212
          True         118
Name: count, dtype: int64

In [21]:
# is there another way to see this?
#using .agg to find counts and averages
squirrels_df.groupby('Age').agg({'Foraging': ['count', 'mean']})

         Foraging
            count      mean
Age
              121  0.355372
?               4  0.250000
Adult        2567  0.495520
Juvenile      330  0.357576

In [22]:
#what days are squirrels most active?
squirrels_df.groupby('Date').agg({'Unique Squirrel ID': ['count'], 'Active': ["mean"]})

         Unique Squirrel ID    Active
                      count      mean
Date
10062018                337  0.943620
10072018                405  0.911111
10082018                285  0.922807
10102018                334  0.952096
10122018                218  0.949541
10132018                434  0.926267
10142018                368  0.937500
10172018                216  0.962963
10182018                200  0.945000
10192018                158  0.898734
10202018                 67  0.910448

In [23]:
#which latitude and longitudes are most common for different fur colors?
squirrels_df.groupby("Primary Fur Color").agg({'X': ['mean'], 'Y': ['mean']})

                           X          Y
                        mean       mean
Primary Fur Color
                  -73.965314  40.783362
Black             -73.965277  40.782340
Cinnamon          -73.969037  40.777929
Gray              -73.967016  40.781194

# Exporting

In [24]:
# export to csv
squirrels_df.to_csv('data/squirrels_cleaned.csv')